- name: Desativando o Swap
  shell: swapoff -a

- name: Instalando o Docker
  shell: curl -fsSL https://get.docker.com | bash -

- name: Setando o cgroupdriver
  copy:
    src: daemon.json
    dest: '/etc/docker/daemon.json'

- name: Criando diretorio
  command: mkdir -p /etc/systemd/system/docker.service.d

- name: Recarregando o daemon
  command: systemctl daemon-reload

- name: Reiniciando o docker
  command: systemctl restart docker

- name: Reiniciando o kubelet
  command: systemctl restart kubelet  

- name: Adicionando as chaves repositorio Kubernetes no apt
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adicionando o repositorio do Kubernetes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Instalando os pacotes do Kubernetes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

